version: '3'

services:
  mailhog:
    container_name: mailhog
    image: mailhog/mailhog
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:21.1.2
    volumes:
      - ./keycloak/v20/imports:/opt/keycloak/data/import
      - ./keycloak/v20/themes/metis:/opt/keycloak/themes/metis
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: Pa55w0rd
    ports:
      - 8080:8080
    command: "start-dev --import-realm"
    depends_on:
      - mailhog